
win:
	gcc -std=c99 -Wall -Wpedantic ../utils.c ../main.c funcs.c -I ../include -o ..\..\build\game.exe
	..\..\build\game.exe
linux:
	gcc -std=c99 -Wall -Wpedantic ../utils.c ../main.c funcs.c -I ../include -o ..\..\build\game -lm
	..\..\build\game
